services:
  - type: web
    name: skillmatch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn skillmatch.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
