# Generated by Django 5.1.4 on 2024-12-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_jobseeker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='job_role',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
