# Generated by Django 5.1.4 on 2025-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0007_rename_available_days_jobseeker_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
