# Generated by Django 5.1.4 on 2025-01-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0009_alter_jobseeker_end_time_alter_jobseeker_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='other_jobs_known',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
