# Generated by Django 5.1.4 on 2024-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_job_seeker',
            field=models.BooleanField(default=False),
        ),
    ]
