# Generated by Django 5.1.4 on 2024-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_customuser_is_job_seeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('area', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('profile', models.ImageField(blank=True, default=None, null=True, upload_to='profile/')),
            ],
        ),
    ]
