# Generated by Django 5.1.4 on 2025-01-07 06:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_jobseeker_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='availability',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='available_days',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 6, 2, 32, 5051, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 7, 6, 3, 4, 685315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='area',
            field=models.CharField(default='tha', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='job_role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(default='75677', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
