# Generated by Django 5.1.4 on 2025-01-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_remove_jobseeker_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='available_days',
            new_name='availability',
        ),
    ]
