# Generated by Django 5.1.4 on 2025-01-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_alter_jobseeker_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
